# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e691255627c1b6401e19795a87d1c574d4e2f0c66f1d8140fac3acb218ced39ccb6221db6861c2aad8dc729e08ee1de12338ecb5680ea2df61cad437b99a032

test:
  secret_key_base: 93d237e30995fc33cbf02193a4a96afcc93057f9a7e917ff56e05a1321e6c0af8c0cbfb33aa4f2d441a743fe813bd058e8241dcd1ae15ada6cf1276a89b3592a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
